export const tagsNSFW: Array<String> = [
  '69',
  'Anal',
  'Asphyxiation',
  'Blowjob',
  'Boobjob',
  'Breast Sucking',
  'Buttjob',
  'Cowgirl',
  'Cunnilingus',
  'Deepthroat',
  'Doggy',
  'Dominant',
  'Double Penetration',
  'Face Sitting',
  'Facial',
  'Feet',
  'Fingering',
  'Fisting',
  'Footjob',
  'Forced',
  'Gore',
  'Grinding',
  'Handjob',
  'Humiliation',
  'Lead In',
  'Lotus Position',
  'Masturbation',
  'Missionary',
  'Oral',
  'Oviposition',
  'Penetration',
  'Prone Bone',
  'Reverse Cowgirl',
  'Reverse Spitroast',
  'Rimming',
  'Ryona',
  'Spanking',
  'Spitroast',
  'Teasing',
  'Toys',
  'Tribadism',
  'Triple Penetration',
  'Vaginal',
];

export const tagsSFW: Array<String> = [
  'Behind',
  'Facing',
  'Holding',
  'Hugging',
  'Kissing',
  'Kneeling',
  'Loving',
  'Lying',
  'Magic',
  'Sitting',
  'Spooning',
  'Standing',
];

/** OStim action types as `action:{type}` tags (roles default on export). */
export const tagsOStimActions: Array<String> = [
  'action:analfingering',
  'action:analfisting',
  'action:anallicking',
  'action:analsex',
  'action:analtailsex',
  'action:analtoying',
  'action:bathing',
  'action:blowjob',
  'action:boobjob',
  'action:breastslapping',
  'action:breastsliding',
  'action:breastsmothering',
  'action:buttjob',
  'action:buttsmothering',
  'action:choking',
  'action:clitoraleating',
  'action:clitorallicking',
  'action:clitoralrubbing',
  'action:cuddling',
  'action:cumonbutt',
  'action:cumonchest',
  'action:cumonvulva',
  'action:dancing',
  'action:deepthroating',
  'action:facial',
  'action:femalemasturbation',
  'action:footjob',
  'action:frenchkissing',
  'action:grindingfoot',
  'action:grindingobject',
  'action:grindingpenis',
  'action:grindingthigh',
  'action:gropingbreast',
  'action:gropingbutt',
  'action:gropingtesticles',
  'action:handjob',
  'action:holdingarm',
  'action:holdingbody',
  'action:holdingchin',
  'action:holdingfoot',
  'action:holdinghand',
  'action:holdinghead',
  'action:holdinghip',
  'action:holdingleg',
  'action:holdingneck',
  'action:holdingthigh',
  'action:hugging',
  'action:kissing',
  'action:kissingcheek',
  'action:kissingfoot',
  'action:kissinghand',
  'action:kissingneck',
  'action:leglocking',
  'action:lickingnipple',
  'action:malemasturbation',
  'action:massaging',
  'action:massagingtail',
  'action:mounting',
  'action:oralfingering',
  'action:oraltoying',
  'action:pattinghead',
  'action:penilelicking',
  'action:pullinghair',
  'action:pullingtail',
  'action:rimjob',
  'action:rubbingpenisagainstface',
  'action:spanking',
  'action:spectating',
  'action:spooning',
  'action:strokinghead',
  'action:strokingtail',
  'action:suckingnipple',
  'action:tailjob',
  'action:testicularlicking',
  'action:thighjob',
  'action:ticklingfoot',
  'action:tribbing',
  'action:vaginalfingering',
  'action:vaginalfisting',
  'action:vaginalsex',
  'action:vaginaltailsex',
  'action:vaginaltoying',
  'action:vampirebiting',
  'action:washing',
];

console.assert(tagsNSFW.length + tagsSFW.length < 64);
